#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Champion and lane-pair tags for the precision recommendation cards.

The recommendation model still works without these tags. This file only adds
human-readable coaching language for common bot-lane picks.
"""

CHAMPION_TAGS = {
    # ADC
    "aphelios": ["发育", "团战", "后期"],
    "ashe": ["功能", "开视野", "消耗"],
    "caitlyn": ["推线", "消耗", "前期压制"],
    "draven": ["对线压制", "滚雪球", "高风险"],
    "ezreal": ["拉扯", "消耗", "安全发育"],
    "jhin": ["控制衔接", "远程消耗", "中期节奏"],
    "jinx": ["发育", "团战", "后期收割"],
    "kaisa": ["爆发", "进场", "中后期"],
    "kalista": ["对线压制", "控龙", "前中期"],
    "kogmaw": ["发育", "保护核心", "后期输出"],
    "lucian": ["爆发换血", "前中期", "抢线"],
    "missfortune": ["团战", "压血线", "中期"],
    "nilah": ["近身爆发", "all-in", "团战"],
    "samira": ["all-in", "收割", "高风险"],
    "senna": ["消耗", "功能", "成长"],
    "sivir": ["清线", "拉扯", "团战"],
    "smolder": ["发育", "成长", "后期"],
    "tristana": ["爆发", "推塔", "all-in"],
    "twitch": ["发育", "隐身找机会", "后期"],
    "varus": ["消耗", "控制衔接", "前中期"],
    "vayne": ["发育", "单点突破", "后期"],
    "xayah": ["反打", "自保", "团战"],
    "zeri": ["拉扯", "发育", "团战"],
    "ziggs": ["推线", "消耗", "控塔"],

    # Support
    "alistar": ["强开", "反开", "游走"],
    "amumu": ["强开", "团控", "all-in"],
    "bard": ["游走", "开团", "节奏"],
    "blitzcrank": ["先手机会", "游走", "高风险"],
    "brand": ["消耗", "压血线", "团战伤害"],
    "braum": ["保护", "反开", "防突进"],
    "janna": ["保护", "反打", "拉扯"],
    "karma": ["抢线", "消耗", "前中期"],
    "leona": ["强开", "all-in", "前期"],
    "lulu": ["保护", "强化核心", "后期团战"],
    "lux": ["消耗", "控制衔接", "压血线"],
    "milio": ["保护", "拉扯", "强化核心"],
    "morgana": ["反开", "免控", "消耗"],
    "nami": ["消耗", "强化普攻", "前中期"],
    "nautilus": ["强开", "控制链", "前中期"],
    "poppy": ["反突进", "保护", "前中期"],
    "pyke": ["游走", "击杀", "高风险"],
    "rakan": ["开团", "反开", "机动"],
    "rell": ["强开", "团控", "all-in"],
    "renata": ["反开", "保护", "团战"],
    "senna": ["消耗", "成长", "功能"],
    "seraphine": ["消耗", "团战", "保护"],
    "sona": ["发育", "团战", "后期"],
    "soraka": ["保护", "续航", "反消耗"],
    "tahmkench": ["保护", "反打", "防突进"],
    "taric": ["反开", "保护", "团战"],
    "thresh": ["先手机会", "保护", "游走"],
    "velkoz": ["远程消耗", "压血线", "技能命中"],
    "xerath": ["远程消耗", "压血线", "推线"],
    "zilean": ["保护", "加速拉扯", "容错"],
    "zyra": ["消耗", "反打", "压线"],
}

COMBO_TAG_OVERRIDES = {
    frozenset(("lucian", "nami")): ["爆发换血", "前中期节奏"],
    frozenset(("lucian", "thresh")): ["先手爆发", "前中期节奏"],
    frozenset(("lucian", "braum")): ["反打换血", "前中期节奏"],
    frozenset(("lucian", "milio")): ["强化换血", "拉扯保护"],
    frozenset(("jinx", "lulu")): ["发育保护", "后期团战"],
    frozenset(("jinx", "thresh")): ["保护发育", "先手衔接"],
    frozenset(("jinx", "braum")): ["发育保护", "反打拉扯"],
    frozenset(("kogmaw", "lulu")): ["保护核心", "后期团战"],
    frozenset(("zeri", "milio")): ["拉扯保护", "团战输出"],
    frozenset(("caitlyn", "lux")): ["推线消耗", "夹子控制"],
    frozenset(("caitlyn", "karma")): ["抢线压制", "前期控龙"],
    frozenset(("caitlyn", "morgana")): ["推线压制", "免控保护"],
    frozenset(("draven", "thresh")): ["击杀压制", "滚雪球"],
    frozenset(("draven", "pyke")): ["击杀压制", "高风险滚雪球"],
    frozenset(("samira", "rell")): ["all-in爆发", "团战进场"],
    frozenset(("samira", "nautilus")): ["all-in爆发", "控制进场"],
    frozenset(("samira", "leona")): ["all-in爆发", "前期击杀"],
    frozenset(("kaisa", "nautilus")): ["控制进场", "中期抓机会"],
    frozenset(("kaisa", "rell")): ["控制进场", "中期抓机会"],
    frozenset(("xayah", "rakan")): ["反打开团", "中期节奏"],
    frozenset(("xayah", "braum")): ["反打保护", "团战站位"],
    frozenset(("varus", "ashe")): ["远程消耗", "控制衔接"],
    frozenset(("jhin", "xerath")): ["远程消耗", "控制衔接"],
    frozenset(("jhin", "karma")): ["远程消耗", "中期节奏"],
    frozenset(("ezreal", "karma")): ["推线消耗", "安全拉扯"],
    frozenset(("ezreal", "bard")): ["安全发育", "游走节奏"],
}
